<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="9" result="Failed" total="9" passed="7" failed="2" inconclusive="0" skipped="0" asserts="10" engine-version="3.7.0.0" clr-version="4.0.30319.42000" start-time="2017-07-31 08:04:04Z" end-time="2017-07-31 08:04:05Z" duration="0.543915">
  <command-line><![CDATA[packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe  SDY.UnitTestProject.sln ]]></command-line>
  <test-suite type="Assembly" id="11-1" name="SDY.UnitTestProject.exe" fullname="C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.UnitTestProject\bin\Debug\SDY.UnitTestProject.exe" testcasecount="0" runstate="NotRunnable" result="Failed" label="Invalid">
    <properties>
      <property name="_SKIPREASON" value="No suitable tests found in 'C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.UnitTestProject\bin\Debug\SDY.UnitTestProject.exe'.&#xA;Either assembly contains no tests or proper test driver has not been found." />
    </properties>
    <reason>
      <message>No suitable tests found in 'C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.UnitTestProject\bin\Debug\SDY.UnitTestProject.exe'.
Either assembly contains no tests or proper test driver has not been found.</message>
    </reason>
  </test-suite>
  <test-suite type="Assembly" id="12-1012" name="SDY.NUnit.Tests2.dll" fullname="C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.NUnit.Tests2\bin\Debug\SDY.NUnit.Tests2.dll" runstate="Runnable" testcasecount="9" result="Failed" site="Child" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.093229" total="9" passed="7" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="10">
    <environment framework-version="3.6.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.15063.0" platform="Win32NT" cwd="C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject" machine-name="PDS-SYS-SDY" user="sdy" user-domain="PLASS" culture="da-DK" uiculture="da-DK" os-architecture="x86" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.7" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="8" />
    </settings>
    <properties>
      <property name="_PID" value="27152" />
      <property name="_APPDOMAIN" value="domain-cff31e76-SDY.NUnit.Tests2.dll" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="12-1013" name="SDY" fullname="SDY" runstate="Runnable" testcasecount="9" result="Failed" site="Child" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.080075" total="9" passed="7" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="10">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="12-1014" name="NUnit" fullname="SDY.NUnit" runstate="Runnable" testcasecount="9" result="Failed" site="Child" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.077089" total="9" passed="7" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="10">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestSuite" id="12-1015" name="Tests2" fullname="SDY.NUnit.Tests2" runstate="Runnable" testcasecount="9" result="Failed" site="Child" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.074069" total="9" passed="7" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="10">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-suite type="TestFixture" id="12-1000" name="NUnitUnitTest1" fullname="SDY.NUnit.Tests2.NUnitUnitTest1" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" testcasecount="9" result="Failed" site="Child" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.070109" total="9" passed="7" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="10">
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-suite type="ParameterizedMethod" id="12-1006" name="NUnit_FireMultipleTimes" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_FireMultipleTimes" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" testcasecount="5" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.024622" total="5" passed="5" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="5">
              <test-case id="12-1001" name="NUnit_FireMultipleTimes(1)" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_FireMultipleTimes(1)" methodname="NUnit_FireMultipleTimes" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="1508134961" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.006859" asserts="1" />
              <test-case id="12-1002" name="NUnit_FireMultipleTimes(2)" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_FireMultipleTimes(2)" methodname="NUnit_FireMultipleTimes" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="1035570693" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.000050" asserts="1" />
              <test-case id="12-1003" name="NUnit_FireMultipleTimes(3)" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_FireMultipleTimes(3)" methodname="NUnit_FireMultipleTimes" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="1119842304" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.000449" asserts="1" />
              <test-case id="12-1004" name="NUnit_FireMultipleTimes(4)" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_FireMultipleTimes(4)" methodname="NUnit_FireMultipleTimes" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="172237377" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.000042" asserts="1" />
              <test-case id="12-1005" name="NUnit_FireMultipleTimes(5)" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_FireMultipleTimes(5)" methodname="NUnit_FireMultipleTimes" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="1403535805" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.000041" asserts="1" />
            </test-suite>
            <test-suite type="ParameterizedMethod" id="12-1009" name="NUnit_TestBugDodges" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TestBugDodges" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.029535" total="2" passed="1" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="2">
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="12-1007" name="NUnit_TestBugDodges(True,False)" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TestBugDodges(True,False)" methodname="NUnit_TestBugDodges" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="1331946847" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.000311" asserts="1" />
              <test-case id="12-1008" name="NUnit_TestBugDodges(False,True)" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TestBugDodges(False,True)" methodname="NUnit_TestBugDodges" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="717972141" result="Failed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.020045" asserts="1">
                <failure>
                  <message><![CDATA[  Expected: True
  But was:  False
]]></message>
                  <stack-trace><![CDATA[ved SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TestBugDodges(Boolean didDodge, Boolean shouldBeDead) i C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.NUnit.Tests2\NUnitUnitTest1.cs:linje 64
]]></stack-trace>
                </failure>
                <assertions>
                  <assertion result="Failed">
                    <message><![CDATA[  Expected: True
  But was:  False
]]></message>
                    <stack-trace><![CDATA[ved SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TestBugDodges(Boolean didDodge, Boolean shouldBeDead) i C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.NUnit.Tests2\NUnitUnitTest1.cs:linje 64
]]></stack-trace>
                  </assertion>
                </assertions>
              </test-case>
            </test-suite>
            <test-case id="12-1010" name="NUnit_TryShootBug" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TryShootBug" methodname="NUnit_TryShootBug" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="142824284" result="Failed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.001800" asserts="1">
              <failure>
                <message><![CDATA[  Expected: True
  But was:  False
]]></message>
                <stack-trace><![CDATA[ved SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TryShootBug() i C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.NUnit.Tests2\NUnitUnitTest1.cs:linje 80
]]></stack-trace>
              </failure>
              <assertions>
                <assertion result="Failed">
                  <message><![CDATA[  Expected: True
  But was:  False
]]></message>
                  <stack-trace><![CDATA[ved SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TryShootBug() i C:\Users\sdy\Documents\Visual Studio 2017\Projects\SDY.UnitTestProject\SDY.NUnit.Tests2\NUnitUnitTest1.cs:linje 80
]]></stack-trace>
                </assertion>
              </assertions>
            </test-case>
            <test-case id="12-1011" name="NUnit_TryShootDodgingBug" fullname="SDY.NUnit.Tests2.NUnitUnitTest1.NUnit_TryShootDodgingBug" methodname="NUnit_TryShootDodgingBug" classname="SDY.NUnit.Tests2.NUnitUnitTest1" runstate="Runnable" seed="265435943" result="Passed" start-time="2017-07-31 08:04:05Z" end-time="2017-07-31 08:04:05Z" duration="0.000186" asserts="2" />
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>